version: "3.1"

services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: nginx.Dockerfile
    volumes:
      - ./:/docker-app
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default
      - ./docker/nginx/nginx.conf:/etc/nginx/sites-available/default
    restart: always
    ports:
      - 8000:80
      - 443
    links:
      - app
    depends_on:
      - app
    networks:
      - nginx-proxy
      - default
  
  app:
    container_name: node
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/docker-app
    command: "npm run start"
    ports: 
      - 3333:3333
    depends_on: 
      - redis-server
    networks: 
      - nginx-proxy
      - default
  
  redis-server:
    container_name: redis
    image: "redis:latest"
    ports:
      - "6379:6379"
  
networks:
  nginx-proxy: